/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.randomnumber;
import java.util.Random;

/**
 *
 * @author Catalin
 */
public class RandomNumberUI extends javax.swing.JFrame {

    /**
     * Creates new form RandomNumberUI
     */
    public RandomNumberUI() {
        initComponents();
        ErrorMsg_1.setVisible(false);
        ErrorMsg_2.setVisible(false);
        ResultLabel.setText(" ");
    }
    
    public static int randInt(int min, int max) {

    Random rand = new Random();
    int randomNum = rand.nextInt((max - min) + 1) + min;

    return randomNum;
}
    
    public boolean isNumeric(String s) {
    return s.matches("\\d+");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextField1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextField2 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Generate_Button = new javax.swing.JButton();
        ErrorMsg_1 = new javax.swing.JLabel();
        ErrorMsg_2 = new javax.swing.JLabel();
        ResultLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        TextField1.setToolTipText("Minimum value");
        jScrollPane1.setViewportView(TextField1);

        TextField2.setToolTipText("Maximum value");
        jScrollPane2.setViewportView(TextField2);

        jLabel2.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        jLabel2.setText("Minimum value");

        jLabel3.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        jLabel3.setText("Maximum value");

        Generate_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/generate_button.png"))); // NOI18N
        Generate_Button.setName("Generate_Button"); // NOI18N
        Generate_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generate_ButtonActionPerformed(evt);
            }
        });

        ErrorMsg_1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        ErrorMsg_1.setForeground(new java.awt.Color(255, 0, 51));
        ErrorMsg_1.setText("Type a valid number!");
        ErrorMsg_1.setName("ErrorMsg_1"); // NOI18N

        ErrorMsg_2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        ErrorMsg_2.setForeground(new java.awt.Color(255, 0, 51));
        ErrorMsg_2.setText("Type a valid number!");
        ErrorMsg_2.setName("ErrorMsg_2"); // NOI18N

        ResultLabel.setBackground(new java.awt.Color(204, 204, 204));
        ResultLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultLabel.setText("555555");
        ResultLabel.setToolTipText("");
        ResultLabel.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Verdana", 2, 11)); // NOI18N
        jLabel4.setText("Number generated: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Generate_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ErrorMsg_2)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ErrorMsg_1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(50, 50, 50))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(ErrorMsg_1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorMsg_2)
                .addGap(20, 20, 20)
                .addComponent(Generate_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Generate_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generate_ButtonActionPerformed
        // TODO add your handling code here:
        ErrorMsg_1.setVisible(false);
        ErrorMsg_2.setVisible(false);
        int x = 1;
        if( isNumeric( TextField1.getText() ) ) // contine cifre
        {
            //TextField1.setText("da");
        }
        else // nu contine cifre
        {
            x = 0;
            ErrorMsg_1.setVisible(true);
           // TextField1.setText("nu");
        }
        
        if( isNumeric( TextField2.getText() ) ) // contine cifre
        {
            int nr1 = Integer.parseInt(TextField1.getText());
            int nr2 = Integer.parseInt(TextField2.getText());
            if(nr1 >= nr2)
            {
                x = 0;
                ErrorMsg_1.setText("This value must be lower than the second value");
                ErrorMsg_1.setVisible(true);
            }
            //TextField1.setText("da");
        }
        else // nu contine cifre
        {
            x = 0;
            ErrorMsg_2.setVisible(true);
           // TextField1.setText("nu");
        }
        
        if(x == 1)
        {
            int nr1 = Integer.parseInt(TextField1.getText()) , nr2 = Integer.parseInt(TextField2.getText());
            int random = randInt(nr1, nr2);
            ResultLabel.setText(Integer.toString(random));
        }
    }//GEN-LAST:event_Generate_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RandomNumberUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RandomNumberUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RandomNumberUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RandomNumberUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RandomNumberUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorMsg_1;
    private javax.swing.JLabel ErrorMsg_2;
    private javax.swing.JButton Generate_Button;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JTextPane TextField1;
    private javax.swing.JTextPane TextField2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
